name: Build Check

on:
    push:
        branches: ["**"]
        tags-ignore: ["v*"] # ignore semantic-release version tags (v1.0.0, v2.3.4, etc.)
    pull_request:

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run Build
              run: npm run build

            - name: Check dist folder exists
              run: |
                  if [ ! -d dist ]; then
                    echo "'dist/' folder not found after build."
                    exit 1
                  fi
                  if [ -z "$(ls -A dist)" ]; then
                    echo "'dist/' is empty."
                    exit 1
                  fi
